import { Desserts } from "./app/shared/models/desserts"
import { Tag } from "./app/shared/models/tag"
export const sample_desserts:Desserts[]=[
    {id:'1',name:'Avacado Mousse',imagePath:'https://media.istockphoto.com/id/616008964/photo/avocado-mousse-with-pistachio.webp?b=1&s=170667a&w=0&k=20&c=nE4kMVvO4l5JNT9yNfxsKGFUB3jIVvSJPlPOmHeelxU=',description: 'This creamy, rich, and healthy avocado mousse made with avocado is paleo, vegan, and gluten free. EASY!',favorite:false,stars:4,ingredients:['Smashed avacados - 300 g','Fresh cream - 500 ml','Icing sugar - 150 g','Egg yolk - 6 nos','Gelatin - 10 g'],methods:['Smash avacados well to form a pulp.','Mix egg yolk and icing sugar together and beat well and add to avacado pulp.','Beat fresh cream well and add to above.','Mix gelatin with 1 tbsp of water and double boil and re mix with above.','Pour the mixture to a vessel or a mould and refrigerate.','When the mus is thickened,mix 1/4 cup fresh cream with 10 g icing sugar and beat well.','With the aid of a nozzle garnish the mousse nicely.'],tags: ['High blood pressure','Obesity','Cholesterol','Gastritis'],calorieAmount:'450 calories',cookTime:'20'},

{id:'2',name:'Cashew Cookies(kaju kukies)',imagePath:'https://media.istockphoto.com/id/1297149775/photo/cashew-nut-cookies-with-milk-on-the-sackcloth-of-the-white-marble-background.webp?b=1&s=170667a&w=0&k=20&c=_MBQpHL7nj3wOZF_BAayzOk3-mThIXccr4Wh54ppyY4=',description: 'Chewy Cashew Cookies are thick, ultra-chewy (obviously), super soft, and require NO chilling time!',favorite:true,stars:3,ingredients:['Flour - 500 g','Eggs - 3 nos','Cashew-roast and powdered - 400 g','Baking powder - 2 tsp','Sugar - 400 g','Vanilla - 2 tsp','Butter - 150 g'],methods:['Combine sugar and butter add egg yolk and beat well.','Combine baking powder and flour and sieve through to a vessel.','Beat egg-white until thickens add to(1) mixing flour little by little.','Then add cashew and vanilla and mix well to make balls of desired size.','Finally bake at 160C until brown.'],tags: ['Pregnancy'],calorieAmount:'480 calories',cookTime:'30'},

{id:'3',name:'Curd Pudding(mikiri pudima)',imagePath:'https://images.unsplash.com/photo-1637264596042-fcf205a81e1e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cHVkZGluZ3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',description: 'Curd Pudding is enriched with many essential vitamins. Very Simple and Easy Recipe with only 4 ingredients.',favorite:false,stars:4,ingredients:['Curd - 400 g','Egg yolk - 4 nos','Sugar - 175 g','Gelatin - 100 g'],methods:['Beat egg yolk adding sugar little by little and when sugar dissolves add curd.','Double boil gelatin adding 1 tbsp of water.','Then add gelatin to egg mixture and mix well.','Transfer the mixture to a tray or a bowl and refrigerate.','Serve with wood apple jam or strawberry sauce.'],tags: ['Pregnancy','High blood pressure','Cholesterol','Gastritis'],calorieAmount:'440 calories',cookTime:'30'},

{id:'4',name:'Banana Chocolate Pudding',imagePath:'https://domesticdreamboat.com/wp-content/uploads/2022/09/Chocolate-Banana-Pudding-cropped.jpg',description: 'This easy chocolate and banana self-saucing chocolate pudding is so delicious. With a luscious chocolate sauce, serve it hot with ice cream.',favorite:false,stars:5,ingredients:['Bananas - 250 g','Egg yolk - 7 nos','Sugar - 200 g','Baking powder - 1 tsp','Flour - 200 g','Banana essence - 1 tsp','Cooking chocolate - 200 g'],methods:['Combine egg yolk with 100 g of sugar and beat until sugar dissolves.','Mix baking powder with flour and sieve.','Cut bananas to small pieces and wash in lime water.','Add 100 g of sugar and smash the plantains.','Cut the chocolate to small pieces.','Add flour and banana essence to egg mixture(1) and again add banana pieces and chocolate.','Finally spread oil paper,transfer the mixture(6) and bake at 160C for about 20mts.'],tags: ['Pregnancy'],calorieAmount:'470 calories',cookTime:'50'},

{id:'5',name:'Dates pudding(rata indi pudima)',imagePath:'https://media.istockphoto.com/id/1079077072/photo/date-cake-with-caramel-topping.webp?b=1&s=170667a&w=0&k=20&c=Q45Er7qRv4lxXordvUGbbvvfeXXehBE_ldiUlbu8sgk=',description: 'Dates pudding is the ultimate share-worthy dessert! It’s rich and sweet with a lusciously smooth butterscotch sauce you can whip up in just 2 minutes.',favorite:true,stars:5,ingredients:['Thinly sliced dates - 250 g','Baking soda - 1 1/2 tsp','Sugar - 250 g','Baking powder - 1 1/2 tsp','Fresh bread crumbs - 100 g','Vanilla - 1 tsp','Eggs - 5 nos'],methods:['Combine butter and sugar add eggs one by one and beat until sugar dissolves.','Mix fresh bread crumbs and baking powder and add to above(1) mixture.','Mix baking soda to dates and add(2) mixture and again add vanilla too.','Finally spread oil paper in a bowl and pour the mixture,cover it with another oil paper and steam.','Serve with custard sauce.'],tags: ['Pregnancy','Diabetics'],calorieAmount:'480 calories',cookTime:'35'},

{id:'6',name:'Aluva',imagePath:'https://milkmaid.lk/sites/default/files/2022-04/thumbnail.jpg',description: 'Aluva is made from mainly rice flour and honey. Also can add cardamom and cashew nuts.',favorite:true,stars:4,ingredients:['Rice flour-roasted - 600 g','Candy powder - 50 g','Sugar - 300 g','Cashew-split - 50 g'],methods:['Mix sugar with water and put to boil for some time.','Add candy to 500 g rice flour,mix adding treacle little by little(1) until thickens.','Spread the left over rice flour in 3/4" thickness on a clean plank.','Mark in diagonal shapes,press pieces of cashew at its centre and cut and separate before the mixture thickens.'],tags: ['Pregnancy'],calorieAmount:'370 calories',cookTime:'60'},

{id:'7',name:'Gingerly balls(tala bola)',imagePath:'https://vasanthamfoods.com/wp-content/uploads/2022/02/909-2.jpg',description: 'Gingerly or gingili balls or rolls, are traditional Sri Lankan sweetmeats, made with sesame seeds, salt and jaggery (palm sugar).',favorite:false,stars:3,ingredients:['Gingerly washed-dried - 200 g','Coconut scraped-dried - 50 g','Jaggery - 200 g','Salt to taste'],methods:['Combine all and pound well.','Shape into domba(1") sized balls.'],tags: ['High blood pressure'],calorieAmount:'380 calories',cookTime:'55'},

{id:'8',name:'Coconut Milk Toffee(pol kiri toffee)',imagePath:'https://milkmaid.lk/sites/default/files/2023-03/Milk-Toffee-thumb.jpg',description: 'Milky tasty and soft coconut milk toffee recipe One of the most cherished milk toffee of whole world. ',favorite:true,stars:5,ingredients:['Sugar - 500 g','Thick milk - 1 cup','Cashew-small pieces - 50 g'],methods:['Pour thick milk with sugar and mix to put to boil stirringly.','When it is thickening add the pieces of cashew and mix well.','When the mix is thickening remove from fire and pour on to a tray.','Allow to spread thinly and mark to squares shape and cut before the mix thickens.'],tags: ['Pregnancy','Gastritis'],calorieAmount:'350 calories',cookTime:'40'},

{id:'9',name:'Helapa',imagePath:'https://1.bp.blogspot.com/-zzAsXPZpl5I/U2FUurnzYLI/AAAAAAAAAis/mxGXTgvM9qg/s1600/Helapa.jpg',description: 'Helapa is a traditional Sri Lankan sweet treat. It is prepared with a combination of kurakkan flour, sugar, cardamom, and grated coconut.',favorite:true,stars:4,ingredients:['Finger millet(kurakkan) flour - 200 g','Scraped coconut - 75 g','Kenda leaves - 12 nos','Sugar - 100 g','Cardamom powder - 1/2 tsp','Water-sufficient quantity','Salt to taste'],methods:['Wash kenda leaves and keep aside.','Combine and mix kurakkan flour,coconut,sugar and cardamom by adding water gradually and prepare a mixture that does not stick to the hands.','Separate about 15 g of the mix and shape into balls.','Place the ball in the middle of kenda leaf and fold the leaf into two and pressing the mix softly.','Then,steam bake for about 10 minutes.'],tags: ['Obesity','Diabetics','Cholesterol'],calorieAmount:'400 calories',cookTime:'60'},
    {id:'13',name:'Ginger Pudding(inguru pudima)',imagePath:'https://img.delicious.com.au/Dw1-fnzf/w1200/del/2020/06/sticky-ginger-pudding-133537-2.jpg',description:'This ginger pudding is made with ginger juice. The mixture will solidify after sitting for a few minutes to give you a super soft and wobbly pudding.',favorite:false,stars:3.5,ingredients:['Ginger dosi with juice(in small pieces) - 250 g','Caramel sugar - 25 ml','Eggs - 5 nos','Butter - 250 g','Baking powder - 2 tsp','Sugar - 250 g','Fresh(white) bread crumbs - 100 g'],methods:['Combine butter and sugar together and adding eggs one by one beat well until sugar dissolves.','Mix fresh white bread crumbs,mix with baking powder and add ginger and caramel sugar.','Cover the bottom of a round vessel with oil paper,pour the mixture covering with another oil paper and steam boil for about 1 hour.','Serve with custard sauce.'],tags: ['Cholesterol'],calorieAmount:'800 calories',cookTime:'40'},
        
    {id:'14',name:'Pineapple Upside Down(annasi udu yatikuru)',imagePath:'https://media.istockphoto.com/id/1371159045/photo/creamy-cake-with-pineapple.webp?b=1&s=170667a&w=0&k=20&c=cwX5-R-Hg71MdajRnarD4UBKSXxttNHJZ0dfpPq1vUM=',description:'An easy to make  classic upside down pineapple recipe which is also perfect when served warmly.It is a dessert that can be made in minutes and once baked can almost disappear in as many minutes.',favorite:false,stars:3,ingredients:['Pineapple sliced - 500 g','Eggs - 5 nos','Butter - 250 g','Vanilla - 1 tsp','Sugar - 250 g','Baking powder - 1/2 tsp','Flour - 250 g','Golden syrup - 100 ml'],methods:['Combine butter sugar together and adding eggs one by one beat well until sugar dissolves.','Combine flour and baking powder and sieve into a vessel.','Mix flour and vanilla to mixture.','Take a round vessel,cover bottom with aluminium foil.','Place pineapple slices on the foil and pour golden syrup on pineapple slices.','Then thinly spread the prepared mixture on above and bake for 45 mts at 160 C.','When baked turn over the entire mixture making the pineapple slices appear on top.'],tags: ['Cholesterol'],calorieAmount:'750 calories',cookTime:'40'},
            
    {id:'15',name:'Watalappan',imagePath:'https://www.dailylife.lk/kitchen/watalappan/images/watalappan.jpg',description:'Watalappan is a coconut custard pudding made of coconut milk or condensed milk, jaggery, cashew nuts, eggs, various spices, including cardamom, cloves, and nutmeg, and sometimes thick pandan juice or grated vanilla pods.It is a super easy-to-make steamed dessert that needs a few simple ingredients and less preparation.',favorite:false,stars:3,ingredients:['Eggs(broken) - 1 cup','Cashew pieces - 200 g','Thick coconut milk - 1 cup','Nutmeg powder - 1/2 tsp','Kitul treacle - 1 cup'],methods:['Combine coconut milk,eggs and treacle,beat without allowing to foam and sieve,add with nutmeg powder.','Transfer the mixture to a vessel and spread cashew over it.','Then steam cook for about 30 mts(Could be prepared double boiled in oven).'],tags: ['Pregnancy'],calorieAmount:'800 calories',cookTime:'40'},
    
    {id:'16',name:'Ginger Toffee(inguru toffee)',imagePath:'https://www.dailylife.lk/kitchen/ginger-toffee/images/ginger-dosi.jpg',description:'Ginger Toffee is a perfect tea time partner that can be made easily with very few ingredients.It is tasty as well as healthy and helps to prevent from many diseases.',favorite:false,stars:2.3,ingredients:['Thinly cut ginger - 50 g','Condensed milk - 1 tin','Sugar - 200 g','Butter - 1 tbsp'],methods:['Combine milk,sugar,and ginger and put to boil,stirring until thickens.','Remove from fire.','Spread mix on to a plank applied with butter.','Cut out the toffee pieces before cooling.'],tags: ['Cholesterol'],calorieAmount:'700 calories',cookTime:'40'},
            
    {id:'17',name:'Coconut Milk Toffee(pol kiri toffee)',imagePath:'https://media.istockphoto.com/id/1182817514/photo/fresh-caramel-fudge-candies-on-a-wooden-plate-with-copy-space-in-marble-background.webp?b=1&s=170667a&w=0&k=20&c=SwAhUbFZeFmTwaVCPpwAFwBidNQCLn0hO-XeAPpK4Ks=',description:'One of the most cherished milk toffee of whole world. Whether it\'s home made or bought from a grocery shop, milk toffee is such a milky, sweet pleasure to indulge everyone. "Kiri Toffee" as it widely called in Sri Lanka, is a popular sweet around the world.',favorite:false,stars:3,ingredients:['Sugar - 500 g','Thick milk - 1 cup','Cashew(small pieces) - 50 g'],methods:['Pour thick milk with sugar and mix to put to boil stirringly.','When it is thickening add the pieces of cashew and mix well.','When the mix is thickening remove from fire and pour on to a tray.','Allow to spread thinly and mark to squares shape and cut before the mix thickens.'],tags: ['Cholesterol'],calorieAmount:'800 calories',cookTime:'40'},
    {id:'18',name:'Bibikkan',imagePath:'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/374344.jpg?resize=1200:*',description:'Traditional Sri Lankan coconut cake, or bibikkan, is a classic sweet typically made for New Year’s celebrations. These vegan sweet goodies are loaded with cashews, dates, and raisins and make the best addition to your next tea party.',favorite:false,stars:3,ingredients:['Wheat flour - 500 g','Cashew pieces - 100 g','Penipol - 400 g','Baking powder - 3 tsp','Sugar - 115 g','Yeast - 1 tsp','Plums - 100 g','Eggs - 1 nos'],methods:['Sieve flour on to mixing bowl.','Add yeast,egg.salt,and 1 tsp sugar and mix softly like mixing flour for rotti.','Cover with a wet cloth and leave for about 30 minutes to rise.','Add 100 g sugar to above and mix till sugar dissolves.','Again add peni pol,plums,cashew and baking powder and mix well.','Spread a plantain leaf or paper with oil paper covering it,then pour the bibikkan mixture thinly and leave for about 1/2 hour.','Bake at 150 C for about 45 minutes.'],tags: ['Cholesterol'],calorieAmount:'900 calories',cookTime:'40'},
]

export const sample_tags:Tag[]=[
    {name:'Diabetics',count:2},
    {name:'Gastritis',count:3},
    {name:'High blood pressure',count:3},
    {name:'Cholesterol',count:8},
    {name:'Obesity',count:2},
    {name:'Pregnancy',count:7}
]