import { Desserts } from "./app/shared/models/desserts"
export const sample_desserts:Desserts[]=[
    {id:'13',name:'Ginger Pudding(inguru pudima)',imagePath:'https://img.delicious.com.au/Dw1-fnzf/w1200/del/2020/06/sticky-ginger-pudding-133537-2.jpg',description:'This ginger pudding is made with ginger juice. The mixture will solidify after sitting for a few minutes to give you a super soft and wobbly pudding.',favorite:false,stars:3,ingredients:['Ginger dosi with juice(in small pieces) - 250 g','Caramel sugar - 25 ml','Eggs - 5 nos','Butter - 250 g','Baking powder - 2 tsp','Sugar - 250 g','Fresh(white) bread crumbs - 100 g'],methods:['Combine butter and sugar together and adding eggs one by one beat well until sugar dissolves.','Mix fresh white bread crumbs,mix with baking powder and add ginger and caramel sugar.','Cover the bottom of a round vessel with oil paper,pour the mixture covering with another oil paper and steam boil for about 1 hour.','Serve with custard sauce.']},
        
    {id:'14',name:'Pineapple Upside Down(annasi udu yatikuru)',imagePath:'https://media.istockphoto.com/id/1371159045/photo/creamy-cake-with-pineapple.webp?b=1&s=170667a&w=0&k=20&c=cwX5-R-Hg71MdajRnarD4UBKSXxttNHJZ0dfpPq1vUM=',description:'An easy to make  classic upside down pineapple recipe which is also perfect when served warmly.It is a dessert that can be made in minutes and once baked can almost disappear in as many minutes.',favorite:false,stars:3,ingredients:['Pineapple sliced - 500 g','Eggs - 5 nos','Butter - 250 g','Vanilla - 1 tsp','Sugar - 250 g','Baking powder - 1/2 tsp','Flour - 250 g','Golden syrup - 100 ml'],methods:['Combine butter sugar together and adding eggs one by one beat well until sugar dissolves.','Combine flour and baking powder and sieve into a vessel.','Mix flour and vanilla to mixture.','Take a round vessel,cover bottom with aluminium foil.','Place pineapple slices on the foil and pour golden syrup on pineapple slices.','Then thinly spread the prepared mixture on above and bake for 45 mts at 160 C.','When baked turn over the entire mixture making the pineapple slices appear on top.']},
            
    {id:'15',name:'Watalappan',imagePath:'https://www.dailylife.lk/kitchen/watalappan/images/watalappan.jpg',description:'Watalappan is a coconut custard pudding made of coconut milk or condensed milk, jaggery, cashew nuts, eggs, various spices, including cardamom, cloves, and nutmeg, and sometimes thick pandan juice or grated vanilla pods.It is a super easy-to-make steamed dessert that needs a few simple ingredients and less preparation.',favorite:false,stars:3,ingredients:['Eggs(broken) - 1 cup','Cashew pieces - 200 g','Thick coconut milk - 1 cup','Nutmeg powder - 1/2 tsp','Kitul treacle - 1 cup'],methods:['Combine coconut milk,eggs and treacle,beat without allowing to foam and sieve,add with nutmeg powder.','Transfer the mixture to a vessel and spread cashew over it.','Then steam cook for about 30 mts(Could be prepared double boiled in oven).']},
    
    {id:'16',name:'Ginger Toffee(inguru toffee)',imagePath:'https://www.dailylife.lk/kitchen/ginger-toffee/images/ginger-dosi.jpg',description:'Ginger Toffee is a perfect tea time partner that can be made easily with very few ingredients.It is tasty as well as healthy and helps to prevent from many diseases.',favorite:false,stars:3,ingredients:['Thinly cut ginger - 50 g','Condensed milk - 1 tin','Sugar - 200 g','Butter - 1 tbsp'],methods:['Combine milk,sugar,and ginger and put to boil,stirring until thickens.','Remove from fire.','Spread mix on to a plank applied with butter.','Cut out the toffee pieces before cooling.']},
            
    {id:'17',name:'Coconut Milk Toffee(pol kiri toffee)',imagePath:'https://media.istockphoto.com/id/1182817514/photo/fresh-caramel-fudge-candies-on-a-wooden-plate-with-copy-space-in-marble-background.webp?b=1&s=170667a&w=0&k=20&c=SwAhUbFZeFmTwaVCPpwAFwBidNQCLn0hO-XeAPpK4Ks=',description:'One of the most cherished milk toffee of whole world. Whether its home made or bought from a grocery shop, milk toffee is such a milky, sweet pleasure to indulge everyone. "Kiri Toffee" as it widely called in Sri Lanka, is a popular sweet around the world.',favorite:false,stars:3,ingredients:['Sugar - 500 g','Thick milk - 1 cup','Cashew(small pieces) - 50 g'],methods:['Pour thick milk with sugar and mix to put to boil stirringly.','When it is thickening add the pieces of cashew and mix well.','When the mix is thickening remove from fire and pour on to a tray.','Allow to spread thinly and mark to squares shape and cut before the mix thickens.']},
            
    {id:'18',name:'Bibikkan',imagePath:'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/374344.jpg?resize=1200:*',description:'Traditional Sri Lankan coconut cake, or bibikkan, is a classic sweet typically made for New Year’s celebrations. These vegan sweet goodies are loaded with cashews, dates, and raisins and make the best addition to your next tea party.',favorite:false,stars:3,ingredients:['Wheat flour - 500 g','Cashew pieces - 100 g','Penipol - 400 g','Baking powder - 3 tsp','Sugar - 115 g','Yeast - 1 tsp','Plums - 100 g','Eggs - 1 nos'],methods:['Sieve flour on to mixing bowl.','Add yeast,egg.salt,and 1 tsp sugar and mix softly like mixing flour for rotti.','Cover with a wet cloth and leave for about 30 minutes to rise.','Add 100 g sugar to above and mix till sugar dissolves.','Again add peni pol,plums,cashew and baking powder and mix well.','Spread a plantain leaf or paper with oil paper covering it,then pour the bibikkan mixture thinly and leave for about 1/2 hour.','Bake at 150 C for about 45 minutes.']},
]