import { Drinks } from "./app/shared/models/drinks"
import { Tag } from "./app/shared/models/tag"

export const sample_drinks:Drinks[]=[
    {id:'1',name:'Mango Drink',imagePath:'https://images.unsplash.com/photo-1546173159-315724a31696?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bWFuZ28lMjBkcmlua3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',description: 'Mango drink is a delicious creamy drink with mango,a little sugar, and a sprinkling of cumin-roasted powder. It is cool and refreshing on a hot day!',favorite:true,stars:5,ingredients:['Kohu amba-half ripe - 4 nos','Sugar - 40 g', 'Cumin-roasted powder - 1 tsp','Water-boil cool - 6 cups','Salt - 1/2 tsp'],methods:['Wash Mangoes,boil and de skin.','Smash boiled mangoes,mix with water and sieve.','Boil the sieved juice in a separate vessel.','Remove scum while boiling,add sugar and take out from fire.','Refrigerate and spread some cumin powder when serving.'],tags: ['Pregnancy','Obesity','Dengue'],calorieAmount:'400 calories',cookTime:'10'},

{id:'2',name:'Watermelon Drink',imagePath:'https://images.unsplash.com/photo-1597306691225-69ef217a43cc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8d2F0ZXJtZWxvbiUyMGRyaW5rfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60',description: 'Delicious and refreshing watermelon juice is a favorite drink in the summertime! It takes minutes to make and is perfect for fruit lovers.',favorite:false,stars:4,ingredients:['Watermelon - 1 kg','Lime juice - 1 tsp','Sugar - 50 g','Salt - 1/2 tsp','Water - 1 cup'],methods:['Wash,peel off and de-seed add water and blend.','Then sieve through the blended juice,add sugar,lime juice and salt and chill'],tags: ['Pregnancy','Obesity','Dengue'],calorieAmount:'350 calories',cookTime:'15'},

{id:'3',name:'Ceylon Olive Drink(veralu beema)',imagePath:'https://i.ytimg.com/vi/iloStjLsReA/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAq3gN5j-_0lb5OKyghNGloY2oc2A',description: 'A healthy drink  which is rich in vitamins needed for you.Short & sweet recipe that you can easily make at home.',favorite:true,stars:3,ingredients:['Olives(veralu) ripe - 500 g','Milk powder - 3 tsp','Sugar - 100 g','Salt - 1/4 tsp','Water-boil cool - 5 cups'],methods:['Wash and de seed olives(veralu).','Add sugar,salt,milk and sufficient water and blend well.','Chill to serve.'],tags: ['Pregnancy','Obesity','Dengue'],calorieAmount:'300 calories',cookTime:'10'},

{id:'4',name:'Waraka Drink(waraka beema)',imagePath:'https://images.unsplash.com/photo-1524156868115-e696b44983db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bWFuZ28lMjBkcmlua3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60',description: 'Waraka is a very tasty fruit.So we can make a delicious healthy drink from this delicious fruit.',favorite:true,stars:5,ingredients:['Waraka(jak) madulu-ripe - 500 g','Several ice cubes','Sugar - 50 g','Salt - 1/4 tsp','Water-boil cool - 4 cups','Lime juice - 1 tsp'],methods:['Cut madulu to pieces,add sugar,water and blend.Then sieve through.','Add lime juice and salt and chill before use'],tags: ['Pregnancy','Obesity','Dengue'],calorieAmount:'430 calories',cookTime:'20'},

{id:'5',name:'Guava Drink(pera beema)',imagePath:'https://media.istockphoto.com/id/1138963277/photo/glass-of-guava-and-slice-of-its-fruit.webp?b=1&s=170667a&w=0&k=20&c=750Nr_SGQ1M_WserIIsvmrdJ-ujUg-tXRbS9tnFlg-E=',description: 'Guava drink is simply fresh guava blended with liquid. Sweetener may be added.',favorite:true,stars:4,ingredients:['Guava-green - 500 g','Salt - 1/2 tsp','Sugar - 30 g','Water-boil cool - 5 cups'],methods:['Wash,de-seed,cut and add water to blend.','Then sieve through the blended juice,add sugar,lime juice and salt and chill.'],tags: ['Pregnancy','Obesity','Dengue'],calorieAmount:'380 calories',cookTime:'15'},
    {id:'6',name:'Coconut Milk Porridge',imagePath:'https://i0.wp.com/sarahjayhealing.com/wp-content/uploads/2020/10/Kola-Kanda-herbal-porridge.jpg?resize=2048%2C1356&ssl=1',description:'Coconut milk porridge is a creamy and comforting dish made by simmering rice or grains in luscious coconut milk, offering a delightful blend of smooth texture and subtle sweetness—a nourishing and soothing treat enjoyed across various cultures. ',favorite:false,stars:3,ingredients:['Raw Rice-100g', 'Water-6 Cups', 'Coconut(thick) milk -1/2 cups', 'Garlic-10g', 'ginger-10g', 'Salt'],methods:['Pick, clean and wash rice well', 'Then boil the rice in water adding salt', 'When the rice is softened, add garlic and ginger', 'Keep boiling until done', 'Transfer rice to a nebiliya adding thick coconut milk', 'Smash the rice grains with a spoon', 'Again boil the rice for about 30 seconds', 'Remove the pieces of ginger before blending'],tags: ['Dengue','Obesity','Diabetics'],calorieAmount:'850 calories',cookTime:'15'},

{id:'7',name:'Finger Millet Flour Porridge',imagePath:'https://thumbs.dreamstime.com/b/ragi-porridge-sweet-ragi-malt-india-ragi-porridge-sweet-ragi-malt-java-healthy-nutritional-drink-made-organic-finger-millet-190005946.jpg?w=768',description:'Finger millet flour porridge is a wholesome and nutritious dish created by cooking finely ground finger millet in water or milk, resulting in a hearty and energy-boosting meal with a nutty flavor profile—a popular choice for its health benefits and satisfying taste. ',favorite:false,stars:3,ingredients:['Finger millet flour-100g', 'Sago-50g', 'Scrapped coconut-50g', 'Water -6 Cups', 'Salt'],methods:['Put finger millet flour into a pot and rub to for small crumbs', 'Squeeze out scrapped coconut to take ½ cups of thick milk', 'Add water to left over coconut and squeeze out 5 cups of thin milk', 'Boil the thin milk and when boiling, add salt, bread crumbs and sago, stirring the mixture slowly', 'When well boiled.add thickmilk and continue stirring for  a few more seconds', 'Remove from the fire, serve warm or chilled'],tags: ['Dengue','Obesity'],calorieAmount:'700 calories',cookTime:'15'},

{id:'8',name:'Bael Fruit Drink',imagePath:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqfpWUeraIeN-dvT6F2wJvh2RhlO0b8uE6xg&usqp=CAU',description:'Bael fruit drink, derived from the ripe fruit of the bael tree, is a refreshing and natural beverage with a unique sweet-tangy flavor, known for its cooling properties and potential health benefits',favorite:false,stars:3,ingredients:['Dry beli flowers-50g', 'Water-4 Cups'],methods:['Wash the dry flowers well', 'Place a pot with water on fire and when boiled washed flowers', 'After 15 minutes , strain and serve with jaggery'],tags: ['Diabetics','Gastritis','High blood pressure'],calorieAmount:'800 calories',cookTime:'25'},

{id:'9',name:'Ginger with Corriander',imagePath:'https://www.dailylife.lk/kitchen/coriander-ginger-drink/images/coriander-ginger-hori.jpg',description:'This is categorized as a medicinal drink and taken at the early stages of sickness like cold,cough and fever.This popular drink eases discomfort occurring during headaches etc.',favorite:true,stars:3,ingredients:['Coriander - 50 g','Water - 4 cups/1000 ml','Ginger - 10 g'],methods:['Wash and drain coriander and roast a little.','Then pour water,add ginger and boil well.','Strain and serve(with or without sugar)hot.'],tags: ['Diabetics','Gastritis','Dengue'],calorieAmount:'700 calories',cookTime:'35'},
       
{id:'10',name:'Wild Mango Fruit Drink(embarella beema)',imagePath:'https://rasakama.files.wordpress.com/2016/12/img_1599.jpg?w=723',description:'This is a popular drink which helps to improve our health.It is specially recommended for diabetic and high blood pressure patients.',favorite:false,stars:3,ingredients:['Wild mango fruits(ripe) - 12 nos','Salt - 1/2 tsp','Water(boil cool) - 6 cups'],methods:['Wash embarella,put it in boiling water and keep for about 1 minute.','Remove and de-skin and cut to pieces.','Add water and blend the cut pieces and put through a sieve.','Add sugar and salt.'],tags: ['Diabetics','Gastritis','High blood pressure'],calorieAmount:'600 calories',cookTime:'15'},
       
{id:'11',name:'Nelli Drink(nelli beema)',imagePath:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9tw-HOFz_FOWjrv_cZQnI6Tw-FAV_z7Hb6SI8aetLNUc51oGDf0LPX0VvHBVf-DdhW-s&usqp=CAU',description:'This drink is one of the drinks with higher medicinal value.It helps to maintain a healthy life.',favorite:true,stars:3,ingredients:['Green coloured nelli - 500 g','Sugar - 100 g','Water(boil cool) - 4 cups','Salt - 1/2 tsp'],methods:['Wash nelli and put into a vessel.','Add lukewarm water and drain out.','Then de-seed,blend and add water and blend again and sieve through.','Add sugar and a little salt to sieve mix and then chill.'],tags: ['Diabetics','Gastritis','High blood pressure','Dengue'],calorieAmount:'850 calories',cookTime:'25'},

{id:'12',name:'Plain conjee',imagePath:'https://dimsumguide.com/fi/plain_congee.jpg ',description: ' Congee, also known as rice porridge, is a comforting Asian dish made by simmering rice in water or broth until it becomes a creamy, thick texture. It is often served plain or with various toppings like green onions, ginger, soy sauce, and meats for added flavor. Congee is a versatile and soothing meal enjoyed across different Asian cultures.',favorite:true,stars:3,ingredients:[ 'Raw rice','Water-6cups','Salt'],methods:['Pick clean and wash rice', 'Boil in 6 cups of water with constant stiring', 'When cooked through ,add salt', 'Remove pan from the fire'],tags: ['High blood pressure','Obesity','Cholesterol', 'Gastritis', 'Diabetes']
    ,calorieAmount:'700  calories',cookTime:'30'},
{id:'13',name:'Polpala conjee',imagePath:'https://www.blog.goserendi.com/wp-content/uploads/2020/10/kola-kanda-1.jpg',description: ' Polpala Kanda is a traditional Sri Lankan herbal porridge made by blending cooked rice, fresh green herbal leaves, and coconut milk. This nutritious dish is known for its potential health benefits and is enjoyed for breakfast.',favorite:false,stars:2,ingredients:[ 'Polpala-250g', 'Kekulu rice-100g', 'Scraped coconut-50g', 'Garlic-10g', 'Ginger-10g', 'Water-6 cups', 'Salt'],methods:['Carefully select plants,clean,wash and cut suitably to  ease pounding', 'Then add ¼ cups of water,mix well,squeeze out and take the juice', 'Repeat pounding once more and add ½ cup of water and extract the juice', 'Now taking rice add water and put to boil', 'Addginger and garlic and leave to boil well', 'Remove boiled rice,crushed or blended and the second squeeze of coconut ,polpala and salt', 'Then put everything to boil stirring thoroughly', 'Add polpala juice and mix and remove the pan from heat', 'Leave it out for like 30 seconds before serving', 'Remove ginger before blending', 'Use kithul juggery when serving'],tags: ['Diabetes','Gastritis','Obesity']
    ,calorieAmount:'400  calories',cookTime:'50'},


{id:'14',name:'Pressed Rice Conjee',imagePath:'https://www.tiger-corporation.com/wp-content/uploads/2023/02/hero-img-recipe-basic-congee-55926a7ae08456507796ce1d2737d445.jpg',description: ' Pressed Rice Congee, also known as Poha Congee, is a dish made by simmering softened flattened rice flakes with vegetables, spices, and seasonings. A quick and flavorful option, it is enjoyed as a light meal or breakfast in Indian and Southeast Asian cuisines.',favorite:false,stars:2,ingredients:[ 'Habala pethi-200g','Fresh milk-1 litre','Sultana-50g', 'Sultana-50g','Ripe banana-4 nos','Salt'],methods:['Immerse habala prhti in water and leave for about 30 seconds and squeeze out the water', 'Slice the plaintains and dip in lime water mixed with lime and remove plantain slices immediately', 'Mis everything and add honey to serve'],tags: ['Diabetes','Gastritis','Obesity']
    ,calorieAmount:'500  calories',cookTime:'60'},


{id:'15',name:'Pinneaple Drink',imagePath:'https://www.alphafoodie.com/wp-content/uploads/2022/02/How-to-Juice-a-Pineapple-Main1.jpeg',description: ' Pineapple Drink is a sweet and tangy tropical beverage made from fresh pineapple. Enjoy its refreshing flavor served chilled, often with ice, for a delightful and cooling experience.',favorite:true,stars:4,ingredients:[ 'Pineapple-500g', 'Sugar-2tbsp', 'Water-3 cups', 'Salt'],methods:['Clean and peel and decore the fruit', 'Cut to small pieces add water and blend', 'Strain,add sugar and mix well', 'Add salt to taste and put to cool'],tags: ['High blood pressure','Cholesterol','Dengue', 'Obesity', 'Pregnancy']
    ,calorieAmount:' 150 calories',cookTime:'15'},

]

export const sample_tags:Tag[]=[
    {name:'Diabetics',count:1},
    {name:'Gastritis',count:0},
    {name:'High blood pressure',count:0},
    {name:'Cholesterol',count:1},
    {name:'Dengue',count:2},
    {name:'Obesity',count:2},
    {name:'Pregnancy',count:5}
]